name: Unlimitiertes Cloudflare Deployment

on:
  push:
    branches:
      - main  # Falls Ihr Haupt-Branch bei GitHub "master" heißt, ändern Sie das hier in master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Code auschecken
        uses: actions/checkout@v4

      - name: Zu Cloudflare Pages hochladen
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy . --project-name="Momentum" --branch="main"
